AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    ask_aircon

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
    Function:
        Timeout: 3


Resources:

    AskAirconFunction:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            CodeUri: ask_aircon/build/
            Handler: app.lambda_handler
            Runtime: python3.6
            Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
                Variables:
                    SLACK_WEBHOOK_URL: VALUE
                    SLACK_CHANNEL: aaaa
            Events:
                Aircon:
                    Type: Schedule # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                    Properties:
                        Schedule: rate(12 hours)

Outputs:
    AskAirconFunction:
      Description: "Ask aircon Lambda Function ARN"
      Value: !GetAtt AskAirconFunction.Arn

    AskAirconFunctionIamRole:
      Description: "Implicit IAM Role created for AskAirconFunction function"
      Value: !GetAtt AskAirconFunctionRole.Arn
