AWSTemplateFormatVersion: '2010-09-09'
Description: Notify Slack Train Delay
Globals:
  Function:
    Timeout: 10
Outputs:
  NotifyPeriodicFunction:
    Description: Notify Periodic Function ARN
    Value:
      Fn::GetAtt:
      - NotifyPeriodicFunction
      - Arn
  NotifyPeriodicFunctionIamRole:
    Description: Implicit IAM Role created for Notify Periodic Function
    Value:
      Fn::GetAtt:
      - NotifyPeriodicFunction
      - Arn
Parameters:
  SlackWebhookUrl:
    Default: hoge
    Type: String
Resources:
  NotifyPeriodicFunction:
    Properties:
      CodeUri: s3://gnk263-lambda-bucket/31f61dbbcdf5f81ad5b91adc0c014799
      Environment:
        Variables:
          SLACK_WEBHOOK_URL:
            Ref: SlackWebhookUrl
      Events:
        NotifySlack:
          Properties:
            Schedule: cron(0 23 * * ? *)
          Type: Schedule
      Handler: periodic.lambda_handler
      Runtime: python3.6
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
